# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Setmore API Tests - Node.js CI

on:
  workflow_dispatch: 
    description: 'Running API tests manually...'
  push:
    branches: [ master,cache-github-actions]
  pull_request:
    branches: [ master ]
    types: [opened]
 

jobs:
  repository:
 
   runs-on : ubuntu-latest
   timeout-minutes: 1
   steps :
         - name: Check out repository
           uses: actions/checkout@v2
           
           with:
            repository: Adaptavant/Setmore-Automation-WebApp
            token: 28e6e3ca516b8b7201401c0409b3f2124b12947e
            event-type: tests
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

                
                
  api-tests:
    runs-on : ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        shell: bash
        working-directory: setmore

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    
